api_description = {
    "endpoints":[
        {"path":"/",
         "method":"GET",
         "description":"API documentation"},
        {"path":"/customers",
         "method":"GET",
         "description":"Lists all customers"},
        {"path":"/customers",
         "method":"POST",
         "required body":{"name":"string","postal_code":"string","phone":"string"},
         "description":"Adds 1 customer"},
        {"path":"/customers/<id>",
         "method":"PUT",
         "required body":{"name":"string","postal_code":"string","phone":"string"},
         "description":"Updates customer with matching id"},
        {"path":"/customers/<id>",
         "method":"GET",
         "description":"Lists information for customer with matching id"},
        {"path":"/customers/<id>",
         "method":"DELETE",
         "description":"Deletes customer with matching id"},
        {"path":"/customers/<id>/rentals",
         "method":"GET",
         "description":"Lists video rentals for customer with matching id"},
        {"path":"/",
         "method":"GET",
         "description":"API documentation"},
        {"path":"/videos",
         "method":"GET",
         "description":"Lists all videos"},
        {"path":"/videos",
         "method":"POST",
         "required body":{"name":"string","postal_code":"string","phone":"string"},
         "description":"Adds 1 video"},
        {"path":"/videos/<id>",
         "method":"PUT",
         "required body":{"title":"string","release_date":"datetime","total_inventory":"integer"},
         "description":"Updates video with matching id"},
        {"path":"/videos/<id>",
         "method":"GET",
         "description":"Lists information for video with matching id"},
        {"path":"/videos/<id>",
         "method":"DELETE",
         "description":"Deletes video with matching id"},
        {"path":"/videos/<id>/rentals",
         "method":"GET",
         "description":"Lists customers who have rented the video with matching id"},
        {"path":"/rentals/check-out",
         "method":"POST",
         "required body":{"customer_id":"integer","video_id":"integer"},
         "description":"Checks out video with matching id to customer with matching id"},
        {"path":"/rentals/check-in",
         "method":"POST",
         "required body":{"customer_id":"integer","video_id":"integer"},
         "description":"Checks in video with matching id for customer with matching id"},
        

    ]
}