"""empty message

Revision ID: 0663be054953
Revises: 6015f9934596
Create Date: 2022-12-21 11:30:54.155918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0663be054953'
down_revision = '6015f9934596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moons', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('moons', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moons', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('moons', 'name')
    # ### end Alembic commands ###
