"""add two more features, remove feature column

Revision ID: 14c33350f28e
Revises: df441b24b5eb
Create Date: 2022-12-22 10:31:27.501582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c33350f28e'
down_revision = 'df441b24b5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('distance_from_earth', sa.Integer(), nullable=True))
    op.add_column('planet', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'size')
    op.drop_column('planet', 'distance_from_earth')
    # ### end Alembic commands ###
