"""add moon model

Revision ID: 17ef30526c93
Revises: fa847ccd285c
Create Date: 2023-01-06 00:16:20.383154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ef30526c93'
down_revision = 'fa847ccd285c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moon', sa.Column('radius', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moon', 'radius')
    # ### end Alembic commands ###
