"""add moon model

Revision ID: 54a0c9193606
Revises: 6b7d7c9c3a37
Create Date: 2023-05-08 17:05:49.066693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a0c9193606'
down_revision = '6b7d7c9c3a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('planet', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('planet', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('planet', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planet', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planet', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('moon')
    # ### end Alembic commands ###
