"""add moon, planet and bodies models

Revision ID: 6015f9934596
Revises: 
Create Date: 2022-12-20 11:05:53.575534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6015f9934596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_bodies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('gravity', sa.Float(), nullable=True),
    sa.Column('escape_velocity', sa.Float(), nullable=True),
    sa.Column('rotation_period', sa.Float(), nullable=True),
    sa.Column('day_length', sa.Float(), nullable=True),
    sa.Column('distance_from_sun', sa.Float(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('orbital_velocity', sa.Float(), nullable=True),
    sa.Column('orbital_inclination', sa.Float(), nullable=True),
    sa.Column('orbital_eccentricity', sa.Float(), nullable=True),
    sa.Column('obliquity_to_orbit', sa.Float(), nullable=True),
    sa.Column('mean_tempurature_c', sa.Float(), nullable=True),
    sa.Column('surface_pressure', sa.Float(), nullable=True),
    sa.Column('global_magnetic_feild', sa.Boolean(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('has_rings', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moons')
    op.drop_table('planets')
    op.drop_table('celestial_bodies')
    # ### end Alembic commands ###
