"""adds Book model

Revision ID: 7ac5fc192ba1
Revises: e3f729e226e4
Create Date: 2023-05-02 16:14:38.680978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac5fc192ba1'
down_revision = 'e3f729e226e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'just_for_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('just_for_test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
