"""change column name

Revision ID: ad5e5f65a1aa
Revises: 3f86dac7d25d
Create Date: 2023-01-02 21:00:55.031373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad5e5f65a1aa'
down_revision = '3f86dac7d25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('distance_from_earth', sa.Float(), nullable=True))
    op.drop_column('planet', 'distance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('planet', 'distance_from_earth')
    # ### end Alembic commands ###
