"""empty message

Revision ID: d663f3f6838e
Revises: 0663be054953
Create Date: 2023-01-05 10:33:17.544793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663f3f6838e'
down_revision = '0663be054953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moons', sa.Column('size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moons', 'size')
    # ### end Alembic commands ###
