"""empty message

Revision ID: dd78a18ec750
Revises: cb9e9f40cfb5
Create Date: 2024-10-30 13:09:41.797436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd78a18ec750'
down_revision = 'cb9e9f40cfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('moons', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('has_flag', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('has_flag')
        batch_op.drop_column('moons')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
