"""adds Book model

Revision ID: e3f729e226e4
Revises: be9dd9e6c9de
Create Date: 2023-05-02 15:50:06.088559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f729e226e4'
down_revision = 'be9dd9e6c9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('just_for_test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'just_for_test')
    # ### end Alembic commands ###
